version: "3.8"
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    volumes:
      - './pihole/etc-pihole:/etc/pihole'
      - './pihole/etc-dnsmasq.d:/etc/dnsmasq.d'
    cap_add:
      - NET_ADMIN
    depends_on:
      - dhcphelper
    dns:
      - 127.0.0.1
      - 1.1.1.3
    environment:
      TZ: 'Europe/Budapest'
      WEBPASSWORD: ${PITT_PIHOLE_PASSWORD}
      ServerIP: 192.168.86.100
      DNS1: 1.1.1.3
      DNS2: 1.0.0.3
      VIRTUAL_HOST: pi.hole
      DNSMASQ_LISTENING: all
    networks:
      backend:
        ipv4_address: '172.31.0.100'
      app: {}
    restart: unless-stopped

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Budapest
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    volumes:
      - ./qbittorrent:/config
      - local-share:/downloads
    ports:
      - 6881:6881
      - 6881:6881/udp
    networks:
      - app
    restart: unless-stopped

  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    ports:
      - 32400:32400
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - VERSION=docker
      - PLEX_CLAIM=${PLEX_CLAIM}
    volumes:
      - ./plex:/config
      - local-share:/tv
      - local-share:/movies
    networks:
      - app
    restart: unless-stopped

  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    volumes:
      - ./uptime-kuma:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - app
    restart: unless-stopped

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/etc-nginx/:/etc/nginx/conf.d/
    ports:
      - "80:80/tcp"
    networks:
      - app
    restart: unless-stopped
    depends_on:
      - qbittorrent
      - pihole
      - plex
      - uptime-kuma

  dhcphelper:
    build: ./dhcp-helper
    container_name: dhcphelper
    restart: unless-stopped
    network_mode: "host"
    command: -s 172.31.0.100
    cap_add:
      - NET_ADMIN

  speedtest:
    container_name: speedtest
    image: henrywhitaker3/speedtest-tracker:latest-arm
    volumes:
      - ./speedtest-config:/config
    environment:
      - OOKLA_EULA_GDPR=true
    networks:
      - app
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "200k"
    restart: unless-stopped

networks:
  backend:
    ipam:
      config:
        - subnet: 172.31.0.0/16
  app: {}

volumes:
  local-share:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: "${PITT_SHARED_FOLDER}"
