version: "3.8"
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    volumes:
      - './pihole/etc-pihole:/etc/pihole'
      - './pihole/etc-dnsmasq.d:/etc/dnsmasq.d'
    cap_add:
      - NET_ADMIN
    depends_on:
      - dhcphelper
    dns:
      - 127.0.0.1
      - 1.1.1.1
    environment:
      TZ: 'Europe/Budapest'
      WEBPASSWORD: ${PITT_PIHOLE_PASSWORD}
      ServerIP: 192.168.86.100
      DNS1: 1.1.1.3
      DNS2: 1.0.0.3
      VIRTUAL_HOST: pi.hole
      DNSMASQ_LISTENING: all
    networks:
      backend:
        ipv4_address: '172.31.0.100'
    restart: unless-stopped

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Budapest
      - WEBUI_PORT=80
      - TORRENTING_PORT=6881
    volumes:
      - /path/to/appdata/config:/config
      - /path/to/downloads:/downloads
    ports:
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped  

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/etc-nginx/:/etc/nginx/conf.d/
    ports:  
      - "80:80/tcp"      

  dhcphelper:
    build: ./dhcp-helper
    restart: unless-stopped
    network_mode: "host"
    command: -s 172.31.0.100
    cap_add:
      - NET_ADMIN

networks:
  backend:
    ipam:
      config:
        - subnet: 172.31.0.0/16

volumes:
  local-share:
    driver: local
    driver_opts: 
      type: 'none'
      o: 'bind'
      device: "${PITT_SHARED_FOLDER}"